salary_box/accountapp/urls.py
from django.urls import path
from django.conf.urls import url
from accountapp import views

app_name = 'accountapp'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', views.log_out, name='logout'),
    url(r'^login/$', views.log_in, name='login'),
]

salary_box/myapp/urls.py
from django.urls import path
from django.conf.urls import url
from myapp import views

app_name = 'myapp'
urlpatterns = [
    url(r'^$', views.company, name='home'),
    url(r'^add-company/$', views.add_company, name='add-company'),
    url(r'^(?P<company_name>[\w\-\ ]+)/delete-company/$', views.delete_company, name='delete-company'),
    url(r'^(?P<id>\d+)/delete-employee/$', views.delete_employee, name='delete-employee'),
    url(r'^(?P<company_name>[\w\-\ ]+)-/update-company/$', views.update_company, name='update-company'),
    url(r'^(?P<company_name>[\w\-\ ]+)-/(?P<id>\d+)-/update-employee/$', views.update_employee, name='update-employee'),
    url(r'^(?P<company_name>[\w\-\ ]+)/add-employee/$', views.add_employee, name='add-employee'),
    url(r'^(?P<company_name>[\w\-\ ]+)/$', views.employee, name='employee'),
]

salary_box/salary_box/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('accounts/', include('accountapp.urls')),
]

salary_box/templates/add_company.html
{% extends 'base.html' %}

{% load custom_tags %} 
    {% block title %}
        {{request.path|remove_slash}} 
    {% endblock %} 
{% block content %}
<div class="d-flex justify-content-center flex-direction-row ">
    <div class="border border-info p-4 rounded">
        <h4 class="text-center text-info" >Add Company</h4>
        <form method="post">
            {% csrf_token %} 
            {{ form.as_p }}
            <div class="d-flex justify-content-end justify-content-between mt-4">
                <a class="text-decoration-none " href="{% url 'myapp:home' %}">
                    <button type="button" class="btn btn-danger ">Close</button>
                </a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

salary_box/templates/add_employee.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block title %} Add Employee {% endblock %}

{% block content %}
<div class="d-flex justify-content-center flex-direction-row">
    <div class="border border-info p-4 rounded">
        <h4 class="text-center text-info" >Add Employee</h4>
        <form method="post">
            {% csrf_token %} 
            {{ form.as_p }}
            <div class="d-flex justify-content-end justify-content-between mt-4">
                <a class="text-decoration-none " href="{{ request.META.HTTP_REFERER }}">
                    <button type="button" class="btn btn-danger ">Close</button>
                </a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

salary_box/templates/alert.html
{% if messages %}
{% for message in messages %}
<div class="container">
  <div
    class="alert {{ message.tags }} alert-dismissible fade show"
    role="alert"
  >
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
    {{ message }}
  </div>
</div>
{% endfor %}
{% endif %}

salary_box/templates/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width={device-width}, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %} {% endblock %}</title>

  </head>
  <body style="background-color: whitesmoke;">
    {% include 'header.html' %}
    {% include 'account/login.html' %}
    {% include 'account/signup.html' %}
      <div class="container">
        {% include 'alert.html' %}
         {% block content %}
         {% endblock %}
      </div>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
  </body>
</html>

salary_box/templates/employee.html
{% extends 'base.html' %} {% load custom_tags %} {% block title %}
{{request.path|remove_slash}} {% endblock %} {% block content %}

<a href="{% url 'myapp:add-employee' request.path|remove_slash %}">
  <button class="btn btn-primary btn-outline-info text-light mb-3">
    Add Employee
  </button>
</a>

{% if employee %}
<div class="center row">
 {% for item in employee %}
<div class="card border border-2 border-info mb-4 m-2 profile-card ">
  <div class="card-block m-3 ">
    <h4 class="card-title text-info">
      <img
        src="https://img.icons8.com/fluent/48/000000/identification-documents.png"
      /> {{item.first_name}} {{item.last_name}}
    </h4>
    <p class="card-text info">Id: {{item.id}}</p>
    <p class="card-text info">Address: {{item.address}}</p>
    <p class="card-text info">Experience: {{item.experience}}</p>

    <div class="text-end actions">
      {% if item.company.user == request.user %}
      <a
        class="card-link text-decoration-none"
        href="{% url 'myapp:update-employee' item.company item.id %}"
      >
        <button class="btn btn-primary pt-1 pb-1">Edit</button>
      </a>
      <a
        class="card-link text-decoration-none"
        href="{% url 'myapp:delete-employee' item.id %}"
      >
        <button class="btn btn-danger pt-1 pb-1">Remove</button>
      </a>
      {% endif %}
    </div>
  </div>
</div>
{% endfor %} 
</div>
{% else %}
<h3 class="text-dark text-center mt-5">No Employee Available</h3>
{% endif %} {% endblock %}

salary_box/templates/header.html
<nav class="navbar navbar-expand-lg navbar-light text-dark fw-light mb-4 p-1 border border-dark shadow">
  <div class="container">
    <a class="navbar-brand text-info p-1" href="{% url 'myapp:home' %}">Salary Box</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'myapp:home' %}">Home</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      <div class="btn-group">
        <button class="btn btn-dark text-light p-1 dropdown-toggle" type="button" id="dropdownMenuClickableOutside"
          data-bs-toggle="dropdown" data-bs-auto-close="inside" aria-expanded="false">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="18" fill="currentColor"
            class="bi bi-person-fill mx-1 mb-2 " viewBox="0 0 16 10">
            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
          </svg>{{ request.user}}
        </button>
        <ul class="dropdown-menu btn-sm text-center mr-2" aria-labelledby="dropdownMenuClickableOutside">
          <li><a class="dropdown-item text-dark" href="{% url 'accountapp:logout' %}">Log Out</a></li>
        </ul>
      </div>
      {% else %}
      <btn class="btn bg-secondary btn-sm px-3 mx-2 text-decoration-none text-light" data-bs-toggle="modal"
        data-bs-target="#login">Log In</btn>
      <btn class="btn bg-primary btn-sm px-3 text-decoration-none text-light" data-bs-toggle="modal"
        data-bs-target="#signup">Sign Up</btn>
      {% endif%}
      {% if user.is_superuser %}
      <a class="nav-link active text-dark" aria-current="page" href="admin/">Admin panel</a>
      {% else %}
      {% endif %}
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

salary_box/templates/home.html
{% extends 'base.html' %} 
{% block title %}Salary Box{% endblock %} 
{% block content%}

{% if  user.is_authenticated %}
<a href="{% url 'myapp:add-company'  %}">
  <button class="btn btn-primary text-light btn-outline-info mb-3">
    Add Company
  </button>
</a>
{% else %}
<button class="btn btn-primary text-light btn-outline-info mb-3" data-bs-toggle="modal" data-bs-target="#login">
  Add Company
</button>
{% endif %}
{% if company %} {% for item in company %}

<div class="card border border-2 border-info mb-4 container cards">
  <a class="text-decoration-none" href="{% url 'myapp:employee' item.name %}">
    <div class="card-block m-3">
      <h4 class="card-title text-info">
        <img
          src="https://img.icons8.com/fluent/48/000000/skyscrapers.png"
        />{{item.name}}
      </h4>
      <p class="card-text info">Founder: {{item.founder|upper}}</p>
      <p class="card-text info">Ref No.: {{item.id}}</p>
      <p class="card-text info">Headquator: {{item.headquator}}</p>
      <p class="card-text info">Fund Raise: {{item.fund_raise}}</p>
      <p class="card-text info">Status: {{item.working}}</p>
      <p class="card-text info">
        Total Employees: {{item.get_employee_count}}
      </p>
      <div class="text-end actions">
        {% if item.user == request.user %}
        <a
        class="card-link text-decoration-none"
        href="{% url 'myapp:update-company' item.name %}"
        >
          <button class="btn border btn-primary pt-1 pb-1">Edit</button>
        </a>
        <a
          class="card-link text-decoration-none"
          href="{% url 'myapp:delete-company' item.name %}"
        >
          <button class="btn btn-danger pt-1 pb-1">Remove</button>
        </a>
        {% else %}
        <p class="text-dark">Created By: <strong>{{item.user}}</strong></p>
        {% endif %}
      </div>
     
    </div>
  </a>
</div>
{% endfor %} 
{% else %}
<h2 class="text-info text-center">No Companys Available</h2>
{% endif %} 
{% endblock %}

salary_box/templates/update_company.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block title %} {{request.path|remove_slash}} {% endblock %}

{% block content %}
<div class="d-flex justify-content-center flex-direction-row">
    <div class="border border-info p-4 rounded">
        <h4 class="text-center text-info" >Update Company</h4>
        <form method="post">
            {% csrf_token %} 
            {{ form.as_p }}
            <div class="d-flex justify-content-end justify-content-between mt-4">
                <a class="text-decoration-none " href="{% url 'myapp:home' %}">
                    <button type="button" class="btn btn-danger ">Cancel</button>
                </a>
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

salary_box/templates/update_employee.html
{% extends 'base.html' %} 
{% load custom_tags %}
{% block title %} {{request.path|remove_slash}} {% endblock %} 
{%block content %}
<div class="d-flex justify-content-center flex-direction-row">
  <div class="border border-info p-4 rounded">
    <h4 class="text-center text-info">Update Employee</h4>
    <form method="post">
      {% csrf_token %} 
      {{ form.as_p }}
      <div class="d-flex justify-content-end justify-content-between mt-4">
        <a class="text-decoration-none" href="{{ request.META.HTTP_REFERER }}">
          <button type="button" class="btn btn-danger">Cancel</button>
        </a>
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}